[tool.poetry]
name = "todoister"
version = "0.1.0"
description = ""
authors = ["Gabriel Lopes Rodrigues <gabriellopes@usp.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
